Repository DorianABDS/memory, pull requests merged in 2025-05, with the labels that each got.

#9 feat(github-action): add linter react
  .github/workflows/ci.yml
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
Labels: enhancement, CI

#10 feat(dependabot): add a dependency automation
  .github/dependabot.yml
Labels: dependabot

#11 docs(readme): add of a readme explaining the project
  README.md
Labels: documentation

#12 Feat/card
  public/card_recto/card_recto.png
  public/card_verso/Hippocampe.png
  public/card_verso/Sirene.png
  public/card_verso/dragon.png
  public/card_verso/hydre.png
  public/card_verso/jormungand.png
  public/card_verso/kraken.png
  public/card_verso/leviathan.png
  public/card_verso/lockhness.png
  src/App.css
  src/App.jsx
  src/card/card.css
  src/card/card.jsx
  src/index.css
  src/main.jsx
Labels: enhancement

#14 Feat/card animation
  index.html
  src/App/App.css
  src/App/App.jsx
  src/card/card.css
  src/card/card.jsx
  src/index.css
  src/main.jsx
Labels: enhancement

#16 feat(button): add reinitialisation of the game
  src/App/App.css
  src/App/App.jsx
  src/components/button.jsx
  src/directive.css
  tailwind.config.js
Labels: enhancement

#17 fix(card): disable drag ghost on cards
  src/App/App.jsx
  src/card/card.jsx
Labels: Fix

#18 fix(image): edit image path to vercel
  src/App/App.jsx
Labels: fix

#19 fix(image): edit card verso path to vercel
  src/App/App.jsx
Labels: fix

#24 Feat/docker
  .dockerignore
  Dockerfile
  docker-compose.yaml
  nginx.conf
Labels: enhancement, docker
